#!/bin/bash
if [ -f ".git/hooks/commit-msg" ]
then
    last_line=$(sed "$"p .git/hooks/commit-msg | grep -o "python")
    if [ "$last_line" == "" ]
    then
        echo "python .git/hooks/check_commit.py $1" >> .git/hooks/commit-msg
    fi
fi
